# Generated by Django 3.1.7 on 2021-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_salad_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='booktable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateTimeField()),
                ('persons', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
