# Generated by Django 3.1.7 on 2021-07-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='message1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='subject1',
        ),
    ]
