# Generated by Django 3.1.7 on 2021-08-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='message',
        ),
    ]
