# Generated by Django 3.1.7 on 2021-08-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20210820_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message1',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='subject1',
            new_name='subject',
        ),
    ]
