# Generated by Django 3.1.7 on 2021-08-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20210820_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='response',
        ),
    ]
