# Generated by Django 3.1.7 on 2021-08-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210820_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booktable',
            new_name='table',
        ),
    ]
