# Generated by Django 3.1.7 on 2021-08-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20210820_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='program',
        ),
    ]
